2025-07-26 12:26:20,902 - ERROR - Vehicle with ID 0gefh1HNrGPfs1lh25dSJ not found
2025-07-26 12:26:20,902 - ERROR - Error in verify_and_add_to_queue: Traceback (most recent call last):
  File "E:\workspace\poc\vehicle_management_system\app\routers\queue_management.py", line 45, in verify_and_add_to_queue
    raise HTTPException(status_code=404, detail="Vehicle not found")
fastapi.exceptions.HTTPException: 404: Vehicle not found

2025-07-26 12:26:33,701 - ERROR - Vehicle with ID 0gefh1HNrGPfs1lh25dSJ not found
2025-07-26 12:26:33,701 - ERROR - Error in verify_and_add_to_queue: Traceback (most recent call last):
  File "E:\workspace\poc\vehicle_management_system\app\routers\queue_management.py", line 45, in verify_and_add_to_queue
    raise HTTPException(status_code=404, detail="Vehicle not found")
fastapi.exceptions.HTTPException: 404: Vehicle not found

2025-07-26 12:28:45,267 - ERROR - Registration number mismatch: expected jk01n8550, got jk01af5986
2025-07-26 12:28:45,267 - ERROR - Error in verify_and_add_to_queue: Traceback (most recent call last):
  File "E:\workspace\poc\vehicle_management_system\app\routers\queue_management.py", line 49, in verify_and_add_to_queue
    raise HTTPException(status_code=403, detail="Registration number mismatch")
fastapi.exceptions.HTTPException: 403: Registration number mismatch

